import React, { useState } from 'react';

import type { ReaderResult } from '../types/reader';

interface Props {
  onSubmit: (url: string) => void;
  isLoading: boolean;
  paperTitle: string;
  result: ReaderResult | null;
  onClear: () => void;
}

const PAPER_BODY = `Abstract

The rapid advancement of deep learning has prompted renewed interest in understanding the theoretical foundations of neural network optimization. In this work, we investigate the asymptotic behavior of stochastic gradient descent (SGD) in non-convex loss landscapes, with particular emphasis on saddle-point avoidance and convergence to local minima. We establish that under mild smoothness and bounded variance conditions, SGD with decaying step sizes converges almost surely to a first-order stationary point. Furthermore, we characterize the escape dynamics from strict saddle points using a perturbation-based framework, extending classical results to the stochastic setting.

1. Introduction

The optimization of high-dimensional non-convex functions arises naturally in modern machine learning, particularly in the training of deep neural networks. Despite the empirical success of gradient-based methods, a rigorous theoretical understanding of their convergence properties in non-convex settings remains elusive. Classical convergence theory for gradient descent relies heavily on convexity assumptions that are rarely satisfied in practice. The loss surfaces of deep neural networks are characterized by an abundance of saddle points, flat regions, and local minima of varying quality.

Stochastic gradient descent, introduced by Robbins and Monro (1951), has emerged as the de facto optimization algorithm for large-scale machine learning. The stochastic nature of the gradient estimates introduces noise into the optimization trajectory, which, paradoxically, can be beneficial: it has been observed empirically that SGD tends to find solutions with better generalization properties than those found by full-batch gradient descent. This observation has motivated a line of theoretical work exploring the implicit regularization effects of SGD.

In this paper, we study the convergence of SGD to first-order stationary points under the following assumptions: (A1) the loss function L : Rⁿ → R is L-smooth, i.e., its gradient is Lipschitz continuous with constant L; (A2) the stochastic gradient estimator g(θ; ξ) satisfies E[g(θ; ξ)] = ∇L(θ) and Var[g(θ; ξ)] ≤ σ² for all θ; (A3) the step sizes {ηₜ} satisfy the Robbins-Monro conditions: Σηₜ = ∞ and Ση²ₜ < ∞.

2. Related Work

The convergence of SGD in non-convex settings has been studied extensively. Ghadimi and Lan (2013) established that SGD with constant step size converges to an ε-stationary point in O(1/ε²) iterations, matching the lower bound for first-order methods. Ge et al. (2015) showed that SGD with perturbations can escape strict saddle points in polynomial time. More recently, Jin et al. (2017) introduced the perturbed gradient descent algorithm and proved that it converges to a second-order stationary point efficiently.

In the context of deep learning, Goodfellow et al. (2015) provided empirical evidence that the loss surfaces of neural networks do not exhibit many poor local minima in high dimensions. Choromanska et al. (2015) formalized this observation using the spin-glass model, showing that local minima are concentrated near the global minimum under certain assumptions. Du et al. (2018) proved that gradient descent can find global minima of overparameterized neural networks in polynomial time, exploiting the over-parameterization to ensure positive definiteness of the Gram matrix.

3. Main Results

Theorem 3.1 (Convergence to Stationary Points). Under assumptions (A1)–(A3), the sequence {θₜ} generated by SGD satisfies:

    lim inf_{t→∞} E[‖∇L(θₜ)‖²] = 0

Proof. Let Φₜ = L(θₜ) denote the loss at iteration t. By the L-smoothness of L and the update rule θₜ₊₁ = θₜ − ηₜg(θₜ; ξₜ), we have:

    Φₜ₊₁ ≤ Φₜ − ηₜ⟨∇L(θₜ), g(θₜ; ξₜ)⟩ + (L/2)η²ₜ‖g(θₜ; ξₜ)‖²

Taking expectations with respect to ξₜ and using assumption (A2):

    E[Φₜ₊₁ | θₜ] ≤ Φₜ − ηₜ‖∇L(θₜ)‖² + (L/2)η²ₜ(‖∇L(θₜ)‖² + σ²)

Summing over t = 0, 1, ..., T−1 and applying the Robbins-Monro conditions yields the desired result. □

Theorem 3.2 (Saddle Point Avoidance). Under assumptions (A1)–(A3) and assuming that all saddle points are strict, SGD avoids strict saddle points with probability one.

4. Experimental Validation

We validate our theoretical results on a series of benchmark tasks including image classification on CIFAR-10 and CIFAR-100, and language modeling on Penn Treebank. All experiments use ResNet-50 and LSTM architectures respectively. We compare SGD with momentum against Adam and Adagrad, measuring convergence speed and final test accuracy.

Our results confirm that SGD exhibits the predicted asymptotic convergence behavior. The training loss curves display the characteristic oscillations associated with stochastic gradient noise, followed by convergence to a region of low curvature. The gradient norm ‖∇L(θₜ)‖ decreases monotonically on average, consistent with Theorem 3.1.

5. Conclusion

We have presented a comprehensive analysis of SGD convergence in non-convex optimization landscapes. Our main contributions are: (i) a proof of almost sure convergence to first-order stationary points under standard assumptions; (ii) a characterization of the escape dynamics from strict saddle points; and (iii) empirical validation on deep learning benchmarks. Future work will explore the connection between the implicit regularization of SGD and the geometry of the loss landscape, as well as extensions to adaptive gradient methods.

References

[1] Robbins, H., & Monro, S. (1951). A stochastic approximation method. The Annals of Mathematical Statistics, 22(3), 400–407.
[2] Ghadimi, S., & Lan, G. (2013). Stochastic first-and zeroth-order methods for nonconvex stochastic programming. SIAM Journal on Optimization, 23(4), 2341–2368.
[3] Ge, R., Huang, F., Jin, C., & Yuan, Y. (2015). Escaping from saddle points — online stochastic gradient for tensor decomposition. COLT 2015.
[4] Jin, C., Ge, R., Netrapalli, P., Kakade, S. M., & Jordan, M. I. (2017). How to escape saddle points efficiently. ICML 2017.
[5] Du, S. S., Zhai, X., Poczos, B., & Singh, A. (2018). Gradient descent provably optimizes overparameterized neural networks. ICLR 2019.`;

export function UrlInput({ onSubmit, isLoading, paperTitle, result }: Props) {
  const [value, setValue] = useState('');

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const trimmed = value.trim();
    if (!trimmed) return;

    if (!trimmed.startsWith('http://') && !trimmed.startsWith('https://')) {
      alert('http:// 또는 https://로 시작하는 URL을 입력하세요.');
      return;
    }
    onSubmit(trimmed);
  }

  const displayTitle = result ? result.title : paperTitle;
  const paragraphs = result
    ? result.content.split('\n\n').map((p) => p.trim()).filter(Boolean)
    : PAPER_BODY.split('\n\n').map((p) => p.trim()).filter(Boolean);
  const metaLine = result
    ? [new URL(result.url).hostname, `${result.wordCount.toLocaleString()} words`, new Date(result.fetchedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })]
    : ['Journal of Artificial Intelligence Research', 'Vol. 47, No. 3 (2024)', 'DOI: 10.1613/jair.1.xxxxx'];

  return (
    <section className="retrieve-section">
      <form onSubmit={handleSubmit} className="url-form">
        <input
          type="url"
          value={value}
          onChange={(e) => setValue(e.target.value)}
          placeholder=""
          className="url-input"
          disabled={isLoading}
          required
        />
        <button type="submit" className="fetch-button" disabled={isLoading}>
          {isLoading ? 'Retrieving...' : 'Retrieve'}
        </button>
      </form>

      <div className="paper-preview">
        <div className="paper-preview-header">
          <h2 className="paper-preview-title">{displayTitle}</h2>
          <div className="paper-preview-meta">
            {metaLine.map((item, i) => (
              <span key={i}>{i > 0 && <span style={{ margin: '0 0.25rem' }}>·</span>}{item}</span>
            ))}
          </div>
        </div>
        <div className="paper-preview-body">
          {isLoading
            ? <p className="paper-loading">Retrieving article...</p>
            : paragraphs.map((p, i) => (
                <p key={i} className={!result && (/^\d+\./.test(p) || p === 'Abstract' || p === 'References') ? 'paper-section-heading' : ''}>
                  {p}
                </p>
              ))
          }
        </div>
      </div>
    </section>
  );
}
